"""world outline/beat + memory consolidated for long-run simulation

Revision ID: 4e1c4e8e9a45
Revises: 4ee0f70164f8
Create Date: 2026-06-23 06:45:30.955130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1c4e8e9a45'
down_revision: Union[str, Sequence[str], None] = '4ee0f70164f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ais_agent_memories', sa.Column('consolidated', sa.Boolean(), nullable=False))
    op.add_column('ais_worlds', sa.Column('outline', sa.JSON(), nullable=True))
    op.add_column('ais_worlds', sa.Column('beat_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ais_worlds', 'beat_index')
    op.drop_column('ais_worlds', 'outline')
    op.drop_column('ais_agent_memories', 'consolidated')
    # ### end Alembic commands ###
