"""character stats + scene day_label for live simulation

Revision ID: 4ee0f70164f8
Revises: 00f20c0f11aa
Create Date: 2026-06-23 02:56:08.256494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee0f70164f8'
down_revision: Union[str, Sequence[str], None] = '00f20c0f11aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ais_characters', sa.Column('stats', sa.JSON(), nullable=True))
    op.add_column('ais_scenes', sa.Column('day_label', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ais_scenes', 'day_label')
    op.drop_column('ais_characters', 'stats')
    # ### end Alembic commands ###
