"""init

Revision ID: 95ef8c2e4e61
Revises: cf7e1fb9704b
Create Date: 2025-12-31 22:26:23.077717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '95ef8c2e4e61'
down_revision: Union[str, Sequence[str], None] = 'cf7e1fb9704b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ais_history', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_column('ais_history', 'identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ais_history', sa.Column('identity', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('ais_history', 'role_id')
    # ### end Alembic commands ###
