"""add worldview background (author-only setting bible)

Revision ID: b150249c1d70
Revises: c8bdd39ac88b
Create Date: 2026-06-23 00:21:26.062684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b150249c1d70'
down_revision: Union[str, Sequence[str], None] = 'c8bdd39ac88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ais_worldviews', sa.Column('background', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ais_worldviews', 'background')
    # ### end Alembic commands ###
