"""init

Revision ID: c82bc04dac62
Revises: 23f99b9533c5
Create Date: 2026-01-07 06:40:35.140711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82bc04dac62'
down_revision: Union[str, Sequence[str], None] = '23f99b9533c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ais_history', sa.Column('role_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ais_history', 'role_name')
    # ### end Alembic commands ###
