"""init

Revision ID: cf7e1fb9704b
Revises: 2b3c86eb9eba
Create Date: 2025-12-29 18:14:23.515006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7e1fb9704b'
down_revision: Union[str, Sequence[str], None] = '2b3c86eb9eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ais_history', sa.Column('identity', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ais_history', 'identity')
    # ### end Alembic commands ###
